[LOGGING]
LEVEL = "INFO"

[CONCURRENCY]
MAX_TASKS = 1
MAX_RETRIES = 3
DELAY_BETWEEN_RETRIES = 5  # sec.

[REQUESTS]
TIMEOUT = 10  # sec.
REQUIRE_PROXY = true

[TWITTER]
AUTO_RELOGIN = true
MAX_UNLOCK_ATTEMPTS = 5

[CAPTCHA]
CAPSOLVER_API_KEY = ""
